{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "app-deportistas-nq",
    "description" : "app-deportistas-nq",
    "contact" : {
      "name" : "nquilpatay",
      "email" : "nahuel.quilpatay@mercadolibre.com"
    },
    "version" : "last"
  },
  "servers" : [ {
    "url" : "http://localhost:8080",
    "description" : "Scope local"
  } ],
  "paths" : {
    "/ping" : {
      "get" : {
        "tags" : [ "ping-controller" ],
        "operationId" : "ping",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : { }
}