create database showroom2;
use showroom2;


INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('001', 'Remera básica', 'Remera', 'Nike', 'Blanco', 'M', 50, 19.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('002', 'Jeans ajustados', 'Pantalón', 'Levis', 'Azul', '32', 30, 59.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('003', 'Camisa de vestir', 'Camisa', 'Calvin Klein', 'Negro', 'L', 20, 39.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('004', 'Short deportivo', 'Short', 'Adidas', 'Gris', 'XL', 40, 29.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('005', 'Sweater con capucha', 'Sweater', 'Puma', 'Rojo', 'S', 15, 49.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('006', 'Falda plisada', 'Falda', 'Zara', 'Negro', 'M', 25, 34.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('007', 'Traje de baño', 'Traje de baño', 'Speedo', 'Azul', 'L', 35, 39.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('008', 'Vestido de fiesta', 'Vestido', 'H&M', 'Dorado', 'S', 10, 79.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('009', 'Chaqueta de cuero', 'Chaqueta', 'Diesel', 'Negro', 'XL', 20, 149.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('010', 'Bufanda de lana', 'Bufanda', 'Gap', 'Gris', 'Única', 60, 14.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('011', 'Pantalones cortos de mezclilla', 'Pantalón', 'American Eagle', 'Azul', '30', 25, 39.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('012', 'Camiseta estampada', 'Remera', 'Hollister', 'Negro', 'M', 20, 29.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('013', 'Vestido casual', 'Vestido', 'Forever 21', 'Rosa', 'S', 15, 24.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('014', 'Zapatos deportivos', 'Calzado', 'Nike', 'Blanco', 'US 9', 30, 79.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('015', 'Gorra de béisbol', 'Accesorio', 'New Era', 'Negro', 'Única', 40, 19.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('016', 'Sudadera con capucha', 'Sweater', 'Under Armour', 'Gris', 'L', 20, 54.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('017', 'Chaleco acolchado', 'Chaleco', 'Columbia', 'Azul', 'XL', 10, 89.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('018', 'Calcetines deportivos', 'Calcetines', 'Adidas', 'Blanco', 'US 10-13', 50, 9.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('019', 'Cinturón de cuero', 'Accesorio', 'Tommy Hilfiger', 'Marrón', '110 cm', 30, 34.99);
INSERT INTO clothes (code, name, type, brand, color, size, quantity, selling_price) VALUES ('020', 'Pantalones de vestir', 'Pantalón', 'Banana Republic', 'Gris', '34x32', 25, 69.99);

INSERT INTO payment_methods (description) VALUES ('Efectivo');
INSERT INTO payment_methods (description) VALUES ('Tarjeta de crédito');
INSERT INTO payment_methods (description) VALUES ('Transferencia bancaria');
INSERT INTO payment_methods (description) VALUES ('Tarjeta de débito');

INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S001', '2023-01-10', 150.50, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S002', '2023-02-11', 220.75, 2);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S003', '2023-03-12', 180.00, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S004', '2023-04-13', 95.25, 3);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S005', '2023-05-14', 310.00, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S006', '2023-06-15', 200.50, 4);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S007', '2023-07-16', 150.75, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S008', '2023-08-17', 175.25, 2);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S009', '2023-09-18', 120.00, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S010', '2023-10-19', 250.00, 3);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S011', '2023-11-20', 180.50, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S012', '2023-12-21', 190.75, 4);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S013', '2024-01-22', 210.25, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S014', '2024-01-23', 160.00, 2);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S015', '2024-02-24', 280.50, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S016', '2024-02-25', 175.75, 3);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S017', '2024-02-26', 195.00, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S018', '2024-02-27', 230.00, 4);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S019', '2024-02-28', 150.25, 1);
INSERT INTO sales (number, date, total, payment_method_id) VALUES ('S020', '2024-02-29', 210.75, 2);

INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (11, 7);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (11, 8);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (12, 8);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (12, 9);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (13, 10);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (13, 11);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (15, 14);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (15, 15);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (16, 16);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (16, 17);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (17, 18);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (17, 19);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (18, 20);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (18, 7);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (19, 8);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (19, 9);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (20, 10);
INSERT INTO sales_clothes (sale_number, clothe_code) VALUES (20, 11);
